# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{packnga}
  s.version = "0.9.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Haruka Yoshihara", "Kouhei Sutou"]
  s.date = %q{2011-08-25}
  s.description = %q{Packnga is an library to translate to many languages by YARD.
}
  s.email = ["yoshihara@clear-code.com", "kou@clear-code.com"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "Gemfile",
    "README.textile",
    "Rakefile",
    "doc/text/lgpl.txt",
    "doc/text/news.textile",
    "doc/text/tutorial.textile",
    "lib/packnga.rb",
    "lib/packnga/document-task.rb",
    "lib/packnga/reference-task.rb",
    "lib/packnga/release-task.rb",
    "lib/packnga/version.rb",
    "lib/packnga/yard-task.rb"
  ]
  s.homepage = %q{http://groonga.rubyforge.org/}
  s.licenses = ["LGPLv2"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{groonga}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An utility library to package i18n-ed library.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyforge>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<test-unit-notify>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rubyforge>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<test-unit-notify>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rubyforge>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<test-unit-notify>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

